logging:
  level:
    org:
      springframework: INFO
    com:
      sap:
        olingo:
          jpa: TRACE      
odata:
  jpa:
    punit_name: Trippin
    root_packages: com.mycompany.group234
server:
  port: 8080
spring:
  datasource:
           driver-class-name: org.postgresql.Driver
           url: jdbc:postgresql://34.230.35.229:5432/postgres
           password: password
           username: postgres
  liquibase:
    change-log: classpath:db/liquibase_changelog.xml
    enabled: true
  servlet:
    multipart:
      enabled: false
eclipselink:
   ddl:
       auto:
            create:
                   delete: false